name = "Light-Archeology"
author = "noah"
version = "1.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bc0394346bc2421185852c0f14f3cd17a914b3ceeccf2c8876d30d57e54b437"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
