name = "Light-Archeology"
author = "noah"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42e6753e506e60461a7854a48e609eb38b9f0ff8cc568143bd6783e394d8a13c"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
