name = "Light-Archeology"
author = "noah"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95268b89bf312a46c39345ac649f67546591be5700781b0c2a602215a866f8b6"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
