name = "Light-Archeology"
author = "noah"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e479daea9011cea855bcb69d469558ab32a6e8e5c21a82b3ff8133d4047cc805"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
