name = "Light-Archeology"
author = "noah"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ef70113232f497ac6746b2c009149a97d3d198844bf20c758be4f2305164c71"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
