name = "Light-Archeology"
author = "noah"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e918004c8f06f5a3cd43c6fe2a1a6a77367ac369b1575de0d0c9cd222e5cc6f4"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
