name = "Light-Archeology"
author = "noah"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa3a76f1e51329debf6ba962633e56f34d1829be493a4b8dc402eb4961ec8dd"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
