name = "Light-Archeology"
author = "noah"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ea9e2a4a66fcb43cdd0bf9f10ccbbe52a86bfd9f89967b21d9e3107e912e5fa"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
