name = "Light-Archeology"
author = "noah"
version = "1.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe5b4c592695ca954f486c2e0c3d115616e51a9f6aa9e54cc5b5d6a0a98de5e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
