name = "Light-Archeology"
author = "noah"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60467ed73d21b5ae4453e20cb8fee79953a5bbd3f47c6753d7a92695161b7e08"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
