name = "Light-Archeology"
author = "noah"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca3b9a961300a2c7258f72480ab952cbf5c2a1d02b69699a6550c6b1c083e4fc"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
